version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: quiz-genius-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz-genius
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
