name: ThinkLix CI Checks


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
   
    runs-on: ubuntu-latest
    
    
    steps:
      
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Setup Node.js and npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' 
          
     
      - name: Install dependencies
        run: npm ci 

     
      - name: Run TypeScript type check
        run: npm run type-check

      
      - name: Run ESLint check
        run: npm run lint
        
      
      - name: Run Next.js build check
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}  
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          UPLOAD_PRESET_NAME: ${{ secrets.UPLOAD_PRESET_NAME }} 
          EMAIL_SERVER_HOST: ${{ secrets.EMAIL_SERVER_HOST }}
          EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}
          EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }}
          EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_SECURE: ${{ secrets.EMAIL_SECURE }}
